### ISSUE TITLE
Camera Events - don't seem to work

### ISSUE THREAD

**Issue by grouchal** [nibi79/synologysurveillancestation#29]
I have yet to find a way to configure the camera events to work - please help. 

I am using openhab 2.3.0 with version `v0.29-alpha` of the plugin.

All is connected correctly - I can setup the home mode and also get images from the camera - I only have a problem with events it seems. I get emails from the Synology when there are events detected but I don't seem to be able to get openhab to recognise the events.

I have a switch setup in the following way:

```java
Switch Garage_Camera_Movement              "Garage Camera Movement"                     (Garage) { channel="synologysurveillancestation:camera:briggology:1:event#motion" }
```
Which I have the following rule setup for:

```java
rule "Send a message when motion is detected in the Garage"
when
    Item Garage_Camera_Movement changed to ON
then    
    sendTelegram("to_Al", "Something is happening in the Garage ");
    sendTelegramPhoto("to_Al", Garage_Current_Image.state.toFullString, "Current view of the Garage")
end
```

I sometimes see some strange errors related to `/proxy` in the openhab.log at the times I think events should be sent - but not always - could these be related?

**Comment by Pavion** [comment]
I'm not using Telegram and so I'm not quite sure, what your proxy issues might be.

Please check first, whether your binding actually receives events from Surveillance Station. 
You can:
- check your openHAB event log, to see whether an event came
- check your Surveillance Station: in Timeline App you should be able to see motion events and their trigger time
- try to place additional logging inside your rule:
https://www.openhab.org/docs/administration/logging.html

Note: the easiest way to test events is to use a manual event item:
```
Switch Garage_Camera_IsRecording              "Garage Camera Is Recording"                     (Garage) { channel="synologysurveillancestation:camera:briggology:1:event#manual" }
```
which should trigger as soon (and stay triggered as long...) as you start an manual record from Live View App of Surveillance Station or turn on the Record Switch:
```
Switch Garage_Camera_Record              "Garage Camera Record"                     (Garage) { channel="synologysurveillancestation:camera:briggology:1:common#record" }
```

If you find a solution, please post it here and close this issue. Otherwise please provide additional information (e.g. log excerpt).

**Comment by Pavion** [comment]
P.S. Please check whether your Event refresh timeout (in the Camera Thing configuration) is not zero and is realistic.

**Comment by grouchal** [comment]
@Pavion The events log doesn't show an event but the Timeline App does and I get an email from the Synology.

The refresh is set to 5 seconds - I have ensured that the movement goes on for a while - could it be that the refresh has to happen exactly when the motion event is triggered?

I also tried setting the refresh to every 1 second with no luck. :-(

**Comment by Pavion** [comment]
5 seconds should be fast enough. If an event is shorter and happens "within" refresh, Switch should still be triggered on -- and then off simultaneous -- thus firing a rule. Lower refresh on the other hand may cause overload. 

Anyway, if you're sure your events are not shown (please check the manual event too), please try to restart the binding from Karaf (or the whole openHAB) and check if it's working then. 
This might point to a suspected too-hard-to-simulate issue with threads dying if running for a very long time.

**------------------------**

After writing all above, I've checked my live setup and guess what, my events were dead as well... 
If you are using `.items` files the easiest way to get it going again is to remove/comment every Event Item, save file, wait short for openHAB to refresh the file, then undo and save again. 
Otherwise, please just restart the binding / openHAB.

Thank you for reporting, I've created a new issue #30 to track it now.

**Comment by grouchal** [comment]
@Pavion I have gone with the hack of using the recording mode - no other events come through.

**Comment by Pavion** [comment]
Please check [Releases](https://github.com/nibi79/synologysurveillancestation/releases) or #30 for a new version, should work now. 

A confirmation would be appreciated, also whether you're using `.items` file for the binding, which I suspect to have been a root cause.
